# Generated by Django 4.0 on 2023-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='verify_credits',
            field=models.IntegerField(default=0),
        ),
    ]
