# Generated by Django 4.0 on 2021-12-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('is_pwned', models.TextField(null=True)),
                ('whois_check', models.TextField(null=True)),
                ('email_scraper', models.TextField(null=True)),
                ('zerobounce_api', models.TextField(null=True)),
                ('google_search', models.IntegerField(null=True)),
                ('additional_emails', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
