# Generated by Django 4.0 on 2021-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_search_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
