# Generated by Django 4.0 on 2022-01-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_avatar_user_google_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='search_credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_plan_at',
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('ACTIVE', 'Plan is active'), ('EXPIRED', 'Plan is expired'), ('PENDING', 'Waiting for payment')])),
                ('search_credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='api.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['status'], name='api_userpla_status_98743b_idx'),
        ),
    ]
