# Generated by Django 4.0 on 2022-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_options_user_unverified_changed_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='whois_check',
        ),
        migrations.AddField(
            model_name='search',
            name='social',
            field=models.TextField(null=True),
        ),
    ]
