# Generated by Django 4.0 on 2022-04-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_search_options_search_google_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='google_emails',
        ),
    ]
