# Generated by Django 4.0 on 2022-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_search_google_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256)),
                ('domain_name', models.CharField(max_length=256)),
                ('result', models.JSONField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['first_name', 'middle_name', 'last_name', 'domain_name'], name='api_searchr_first_n_64c56a_idx'),
        ),
    ]
