# Generated by Django 4.0 on 2022-05-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_search_result_on_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFinderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('ZERO_BOUNCE', 'Check valid using zerobounce api'), ('CHECK_PWN', 'Check if emails are pwned'), ('CHECK_SOCIAL', 'Check emails on twitter, microsoft,..'), ('GOOGLE_SEARCH', 'Search emails using google search api')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchresult')),
            ],
        ),
    ]
