# Generated by Django 4.0 on 2023-01-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_emailfinderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonuser',
            name='number_searches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
