# Generated by Django 4.0 on 2022-08-03 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_emailfinderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(max_length=256, null=True)),
                ('done', models.BooleanField(default=False)),
                ('coins', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeadPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('domain_name', models.CharField(max_length=256)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='leadperson',
            index=models.Index(fields=['uuid', 'domain_name'], name='api_leadper_uuid_baa811_idx'),
        ),
        migrations.AddField(
            model_name='leadexport',
            name='people',
            field=models.ManyToManyField(related_name='exports', to='api.LeadPerson'),
        ),
        migrations.AddField(
            model_name='leadexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exports', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='leadexport',
            index=models.Index(fields=['user'], name='api_leadexp_user_id_2c976f_idx'),
        ),
    ]
