# Generated by Django 4.0 on 2022-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_leadexport_leadperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadexport',
            name='download',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='leadexport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
