# Generated by Django 4.0 on 2023-01-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_number_searches'),
        ('api', '0015_leadexport_download_alter_leadexport_id'),
    ]

    operations = [
    ]
