# Generated by Django 4.0 on 2023-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20230104_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptOutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('email', models.EmailField(db_index=True, max_length=100)),
            ],
        ),
    ]
