# Generated by Django 4.0 on 2023-02-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_optoutrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='job_title',
        ),
    ]
