# Generated by Django 4.0 on 2023-03-04 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_first_name_contact_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anonuser',
            name='api_anonuse_token_cda790_idx',
        ),
        migrations.RemoveField(
            model_name='anonuser',
            name='search_credits',
        ),
        migrations.RemoveField(
            model_name='anonuser',
            name='token',
        ),
        migrations.RemoveField(
            model_name='anonuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='anonuser',
            name='number_verifiers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anonuser',
            name='restore_searches_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anonuser',
            name='restore_verifiers_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anonuser',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
