# Generated by Django 4.0 on 2023-03-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_anonuser_api_anonuse_token_cda790_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfinderhistory',
            name='task',
        ),
        migrations.AddField(
            model_name='emailfinderhistory',
            name='search_result',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.searchresult'),
        ),
    ]
