# Generated by Django 4.0 on 2023-04-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_emailfinderhistory_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadexport',
            name='people',
        ),
        migrations.RemoveField(
            model_name='leadexport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='searchresult',
            name='api_searchr_first_n_64c56a_idx',
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['first_name', 'middle_name', 'last_name', 'domain_name'], name='search_resu_first_n_302649_idx'),
        ),
        migrations.AlterModelTable(
            name='anonuser',
            table='anon_user',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='emailfinderhistory',
            table='email_finder_history',
        ),
        migrations.AlterModelTable(
            name='optoutrequest',
            table='opt_out_request',
        ),
        migrations.AlterModelTable(
            name='search',
            table='search',
        ),
        migrations.AlterModelTable(
            name='searchresult',
            table='search_result',
        ),
        migrations.DeleteModel(
            name='LeadExport',
        ),
        migrations.DeleteModel(
            name='LeadPerson',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
