# Generated by Django 4.0 on 2023-04-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_leadexport_people_remove_leadexport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='from_bulk_search',
            field=models.BooleanField(default=False),
        ),
    ]
